name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Where the hell am i?
      run: ls
      
    - name: Pull Front End Code
      uses: actions/checkout@v2
      with:
        repository: teamgrow/frontend
        token: ${{ secrets.the_pat }} 
        path: frontend
        ref: stg

    - name: Install NPM v8.11
      uses: actions/setup-node@v1
      with:
        node-version: '8.11'

    - name: Install Angular
      run: npm install -g @angular/cli@7.3.1      
      
    - name: NPM install...
      run: cd ./frontend && npm install 

   # - name: Build frontend
   #   run: cd ./frontend && ng build --prod
    - name: Where the hell am i now?
      run: ls




